/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Compute the Blob content address (`"algo:hex"`) of the given bytes. */
export declare function blobDigest(data: Uint8Array): string

/** The library version. */
export declare function version(): string
