/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** The library version (e.g. `"0.0.0"`). */
export declare function version(): string
/** Compute the Blob content address (`"algo:hex"`) of the given bytes. */
export declare function blobDigest(data: Uint8Array): string
