/* Uldren Loom C ABI. Generated by cbindgen - do not edit by hand.
 * Licensed under BUSL-1.1. (c) Uldren Technologies LLC. */

#ifndef ULDREN_LOOM_H
#define ULDREN_LOOM_H

/* This file is auto-generated. Regenerate with `just header`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the library version as a newly-allocated C string. Free with [`loom_string_free`].
 */
char *loom_version(void);

/**
 * Compute the Blob content address (`"algo:hex"`) of `len` bytes at `data` and return it as a
 * newly-allocated C string (free with [`loom_string_free`]). Returns null on invalid input.
 *
 * # Safety
 * `data` must point to at least `len` readable bytes, or be null when `len == 0`.
 */
char *loom_blob_digest(const unsigned char *data, uintptr_t len);

/**
 * Free a string previously returned by this library. Passing null is a no-op.
 *
 * # Safety
 * `s` must be a pointer returned by this library and not previously freed.
 */
void loom_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ULDREN_LOOM_H */
