package ai.uldren.loom.rn

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableArray

// `NativeUldrenLoomSpec` is generated by React Native codegen from src/NativeUldrenLoom.ts
// (new architecture). The native methods are implemented by src/main/cpp/UldrenLoom.cpp.
class UldrenLoomModule(reactContext: ReactApplicationContext) :
    NativeUldrenLoomSpec(reactContext) {

    override fun getName(): String = NAME

    override fun version(): String = nativeVersion()

    override fun blobDigest(bytes: ReadableArray): String {
        val out = ByteArray(bytes.size())
        for (i in 0 until bytes.size()) {
            out[i] = bytes.getInt(i).toByte()
        }
        return nativeBlobDigest(out)
    }

    private external fun nativeVersion(): String

    private external fun nativeBlobDigest(data: ByteArray): String

    companion object {
        const val NAME = "UldrenLoom"

        init {
            System.loadLibrary("uldren_loom_rn")
        }
    }
}
